### ISSUE TITLE
Refactor duplicated code to service architecture

### ISSUE THREAD

**Issue by calebanthony** [pbbg/topsite#44]
This is more for the strategy to refactor some duplicated code out into their own classes. This will make the codebase more testable, easier to reason about, and a lot cleaner.

There are several pieces around the codebase where code is copy-pasted, sometimes identically and sometimes with very minor differences.

For example, building out the category array:
```
$categories = [];
$categories["none__"] = "-- Select Category --";
$categories = array_merge($categories, Category::all()->pluck('name', 'slug')->toArray());
```

My suggestion is to refactor this out into a service class architecture. I'd also be happy to tackle this if it's the direction the team wants to go.

What this would look like is:
1. Creating an `app/Services` folder to house our services.
2. Build out classes that are focused on a specific feature, perhaps a `CategoryService.php`.
3. In the controller methods where the abstracted code was used, use Laravel's service container to inject the service class:
```
public function edit(Game $game, CategoryService $categoryService): View
{
    $categories = $categoryService->buildArray();
    ....
}
```

Then we write a unit test for the `CategoryService` methods, making sure the outputs are what we expect.

**Comment by 1e4** [comment]
This makes a while lot of sense to me. Likewise with handling images and such there is various copy and paste for that, I did create an ImageUploadController but with banners it's C+P, so yes, I agree with this completely and it should be done.

Can you think of any more uses for it?

On a counter point, should this be in the Modal? For instance `Category::dropDown()` or do you think it's still best suited outside of the Modal and in it's own service?

We currently use [laravel-bootstrap-4-forms](https://github.com/netojose/laravel-bootstrap-4-forms) and there seems to be a bug in which you can't pass in the key properly to build a select menu, hence why they are also currently using slugs (Not ideal, but I don't see it making a difference right now). Just thought I'd share the backstory on that.

**Comment by 1e4** [comment]
Makes sense, thanks for explaining. You are more than welcome to go ahead with the Service idea. I'll be working on #34 on a new branch in the meantime.
