### ISSUE TITLE
Can't upload an avatar

### ISSUE THREAD

**Issue by matronator** [pbbg/topsite#53]
Every time I try to "Select new photo" on the user settings page, it just throws a 404 in the console(1) and sets my avatar to "not found"(2).

\[1\]:
<img width="1280" alt="404 error" src="https://user-images.githubusercontent.com/5470780/79067888-22a61c80-7cc3-11ea-8a5a-4c7912e065c1.png">

\[2\]:
<img width="54" alt="not found" src="https://user-images.githubusercontent.com/5470780/79067887-1fab2c00-7cc3-11ea-9c68-5c2081619c22.png">

**Comment by 1e4** [comment]
This is the wrong repository for that issue, pbbg.com doesn't use this on pbbg.com
